/**
 * Read all rows from local SQLite (prisma/dev.db) and emit a single .sql file
 * with INSERT statements. Run on the cloud D1 via:
 *
 *   wrangler d1 execute word-sprint-db --remote --file=./d1_seed.sql
 *
 * This file only contains DML (INSERTs). Schema is created separately via
 * `wrangler d1 migrations apply`.
 */

import 'dotenv/config'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function sqlValue(v: unknown): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? '1' : '0'
  if (v instanceof Date) return `'${v.toISOString().replace('T', ' ').replace('Z', '')}'`
  return `'${String(v).replace(/'/g, "''")}'`
}

function buildInsert(table: string, rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return `-- ${table}: (empty)`
  const cols = Object.keys(rows[0])
  const lines = rows.map((row) => {
    const values = cols.map((col) => sqlValue(row[col])).join(', ')
    return `INSERT INTO ${table} (${cols.map((c) => `"${c}"`).join(', ')}) VALUES (${values});`
  })
  return `-- ${table}: ${rows.length} rows\n${lines.join('\n')}`
}

async function main() {
  const users = await prisma.user.findMany()
  const folders = await prisma.folder.findMany()
  const notes = await prisma.note.findMany()
  const expressionFolders = await prisma.expressionFolder.findMany()
  const words = await prisma.word.findMany()
  const reviews = await prisma.review.findMany()
  const expressions = await prisma.expression.findMany()
  const aiUsageLogs = await prisma.aiUsageLog.findMany()

  const sql = [
    '-- Generated by exportSqliteToD1Sql.ts',
    '-- Apply via: wrangler d1 execute word-sprint-db --remote --file=./d1_seed.sql',
    'PRAGMA defer_foreign_keys = ON;',
    '',
    buildInsert('User', users as unknown as Record<string, unknown>[]),
    '',
    buildInsert('Folder', folders as unknown as Record<string, unknown>[]),
    '',
    buildInsert('Note', notes as unknown as Record<string, unknown>[]),
    '',
    buildInsert('ExpressionFolder', expressionFolders as unknown as Record<string, unknown>[]),
    '',
    buildInsert('Word', words as unknown as Record<string, unknown>[]),
    '',
    buildInsert('Review', reviews as unknown as Record<string, unknown>[]),
    '',
    buildInsert('Expression', expressions as unknown as Record<string, unknown>[]),
    '',
    buildInsert('AiUsageLog', aiUsageLogs as unknown as Record<string, unknown>[]),
    '',
  ].join('\n')

  const outPath = resolve(process.cwd(), 'd1_seed.sql')
  writeFileSync(outPath, sql, 'utf8')
  console.log(`Wrote ${outPath}`)
  console.log(
    `Counts → User=${users.length}, Folder=${folders.length}, Note=${notes.length}, ` +
      `ExpressionFolder=${expressionFolders.length}, Word=${words.length}, Review=${reviews.length}, ` +
      `Expression=${expressions.length}, AiUsageLog=${aiUsageLogs.length}`,
  )
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
